title: Mi Documentación - Erronka 3
theme: minima
header_pages:
  - index.md
  - gallery.md
  - dillinger_sample.md
  - Dokumentazioa.md
  - Aurkibidea.md
  - sareen_planifikazioa.md
  - sistema_eragileak.md
  - markatze_lengoaiak.md
  - digitalizazioa.md
  - datu_baseak.md
