title: Mi Documentación - Erronka 3
theme: minima
header_pages:
  - index.md
  - gallery.md
  - dillinger_sample.md
  - Dokumentazioa.md
  - Aurkibidea.md
  - sareen planifikazioa.md
  - Sistema_eragileak.md
  - Markatze_lengoaiak.md
  - Digitalizazioa.md
  - Datu_baseak.md
