title: Mi Documentación - Erronka 3
theme: minima
header_pages:
  - index.md
  - gallery.md
  - dillinger_sample.md
  - Dokumentazioa.md
  - Aurkibidea.md
  - Sareen_planifikazioa.md
  - Sistema_eragileak
  - Markatze_lengoaiak
  - Digitalizazioa
  - Datu_baseak
